### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug' when creating new container

### ISSUE THREAD

**Issue by HeyBanditoz** [ptpb/pb#248]
Perhaps I missed something in the README? Or with docker? I'm unable to launch the container with a fresh docker installation.
* Docker version 18.09.2, build 6247962
* docker-compose version 1.24.0, build 0aa59064
```
# git clone https://github.com/ptpb/pb
# cd pb
# systemctl start docker
# docker-compose up
Creating network "pb_default" with the default driver
Building pb
Step 1/5 : FROM python:3.6-alpine
3.6-alpine: Pulling from library/python
bdf0201b3a05: Pull complete
59c926705abf: Pull complete
dd4853571cc7: Pull complete
3a45eb710779: Pull complete
ace61d116e35: Pull complete
Digest: sha256:8f9fa29cd9d2e1c8b762ddfecc4871fe5a3e8444ec3a2b57d2b6f2a172c4cd50
Status: Downloaded newer image for python:3.6-alpine
 ---> 148efb059c7f
Step 2/5 : WORKDIR /pb
 ---> Running in 0eae786810b2
Removing intermediate container 0eae786810b2
 ---> 8b8ee9787d9b
Step 3/5 : ADD . /build
 ---> ecad079f2931
Step 4/5 : RUN apk add --no-cache --virtual .build-deps git     && pip install /build     && apk del .build-deps
 ---> Running in 84688b100d4d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/6) Installing nghttp2-libs (1.35.1-r0)
(2/6) Installing libssh2 (1.8.2-r0)
(3/6) Installing libcurl (7.64.0-r1)
(4/6) Installing pcre2 (10.32-r1)
(5/6) Installing git (2.20.1-r0)
(6/6) Installing .build-deps (0)
Executing busybox-1.29.3-r10.trigger
OK: 32 MiB in 40 packages
Processing /build
Building wheels for collected packages: pb
  Building wheel for pb (setup.py): started
  Building wheel for pb (setup.py): finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-0tpcdqim/wheels/87/a5/29/40c8cc7ca875b4f3571ab5021ae088b92bae51690cd348fd93
Successfully built pb
Installing collected packages: pb
Successfully installed pb-0.8.1.dev3+g9fec576
WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory
(1/6) Purging .build-deps (0)
(2/6) Purging git (2.20.1-r0)
(3/6) Purging libcurl (7.64.0-r1)
(4/6) Purging nghttp2-libs (1.35.1-r0)
(5/6) Purging libssh2 (1.8.2-r0)
(6/6) Purging pcre2 (10.32-r1)
Executing busybox-1.29.3-r10.trigger
OK: 18 MiB in 34 packages
Removing intermediate container 84688b100d4d
 ---> 273b303aabbb
Step 5/5 : CMD ["python", "-m", "pb"]
 ---> Running in 25d52d16894d
Removing intermediate container 25d52d16894d
 ---> 1fb596aec5a8
Successfully built 1fb596aec5a8
Successfully tagged pb_pb:latest
WARNING: Image for service pb was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling mongodb (mongo:latest)...
latest: Pulling from library/mongo
34667c7e4631: Pull complete
d18d76a881a4: Pull complete
119c7358fbfc: Pull complete
2aaf13f3eff0: Pull complete
f7833eaffdda: Pull complete
8287cb5b9daf: Pull complete
3f92d9c8d3be: Pull complete
c8a99ed04127: Pull complete
7c26ac89d736: Pull complete
f6f01a3e0a56: Pull complete
ff5825a76fb6: Pull complete
0af8892a044b: Pull complete
33eada78dbf2: Pull complete
Digest: sha256:68209a50d83c8e37f3f2dca6d2a69b1c84c57dbae7d74a47640434f2678ae13a
Status: Downloaded newer image for mongo:latest
Creating pb_mongodb_1 ... done
Creating pb_pb_1      ... done
Attaching to pb_mongodb_1, pb_pb_1
pb_1       | Traceback (most recent call last):
pb_1       |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
pb_1       |     "__main__", mod_spec)
pb_1       |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
pb_1       |     exec(code, run_globals)
pb_1       |   File "/pb/pb/__main__.py", line 29, in <module>
pb_1       |     from werkzeug.serving import run_simple
pb_1       | ModuleNotFoundError: No module named 'werkzeug'
mongodb_1  | 2019-04-18T22:33:29.885+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=74dabf34d983
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] db version v4.0.9
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] git version: fc525e2d9b0e4bceff5c2201457e564362909765
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] modules: none
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] build environment:
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongodb_1  | 2019-04-18T22:33:29.899+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongodb_1  | 2019-04-18T22:33:29.901+0000 I STORAGE  [initandlisten]
mongodb_1  | 2019-04-18T22:33:29.901+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongodb_1  | 2019-04-18T22:33:29.901+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongodb_1  | 2019-04-18T22:33:29.901+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=256M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
pb_pb_1 exited with code 1
mongodb_1  | 2019-04-18T22:33:30.704+0000 I STORAGE  [initandlisten] WiredTiger message [1555626810:704286][1:0x7f5a1b5dda80], txn-recover: Set global recovery timestamp: 0
mongodb_1  | 2019-04-18T22:33:30.713+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongodb_1  | 2019-04-18T22:33:30.728+0000 I CONTROL  [initandlisten]
mongodb_1  | 2019-04-18T22:33:30.729+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongodb_1  | 2019-04-18T22:33:30.729+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongodb_1  | 2019-04-18T22:33:30.729+0000 I CONTROL  [initandlisten]
mongodb_1  | 2019-04-18T22:33:30.735+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: a9ca6963-19f6-4da8-8bd0-dfe42d36cd83
mongodb_1  | 2019-04-18T22:33:30.746+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
mongodb_1  | 2019-04-18T22:33:30.758+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 82a537a4-cf77-47bd-abad-89a11041720a
mongodb_1  | 2019-04-18T22:33:30.769+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongodb_1  | 2019-04-18T22:33:30.771+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongodb_1  | 2019-04-18T22:33:30.776+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 7835a3ea-a9a8-4e1e-878c-44f82d28e6d3
mongodb_1  | 2019-04-18T22:33:30.794+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
mongodb_1  | 2019-04-18T22:33:30.795+0000 I INDEX    [LogicalSessionCacheRefresh]        building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2019-04-18T22:33:30.796+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
```

**Comment by qlyoung** [comment]
+1, same issue on vanilla Ubuntu 18.04

**Comment by lxwang42** [comment]
change Dockerfile line 7 to
    && pip install -r /build/requirements.txt \
will solve the problem

**Comment by buhman** [comment]
thanks for reporting; fixed in 4b1cd3b

**Comment by HeyBanditoz** [comment]
Did not fix. Running same set of commands as in OP, same error.

**Comment by buhman** [comment]
@HeyBanditoz you'll need to rebuild your container, as docker-compose/docker will keep the previous build results. You can do this with:

```
docker-compose up --force-recreate --build
```

If this doesn't work, please provide your build [output](https://gist.github.com/buhman/68ffcfea90ddfe2c6630c653b6abec44).

**Comment by HeyBanditoz** [comment]
That worked. Thanks again!
